'use client';
import {useEffect,useState} from 'react';

type Source={name:string,status:'AVAILABLE'|'PENDING',detail:string};
const sources:Source[]=[
{name:'BMA Water / DDS',status:'PENDING',detail:'รอ verified machine endpoint; ไม่ใช้ค่าที่เดา'},
{name:'BMA Radar',status:'PENDING',detail:'เตรียม adapter สำหรับข้อมูลเรดาร์ real-time'},
{name:'ThaiWater',status:'AVAILABLE',detail:'Public water-level integration layer'},
{name:'TMD',status:'PENDING',detail:'รอ API credential / verified contract'},
{name:'GISTDA FloodCheck',status:'PENDING',detail:'รอ API key สำหรับ location-based flood data'},
{name:'Road Flood Sensors',status:'PENDING',detail:'เตรียม nearby sensor integration'}];
export default function Home(){const[now,setNow]=useState('');const[refreshing,setRefreshing]=useState(false);useEffect(()=>setNow(new Date().toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})),[]);function refresh(){setRefreshing(true);setTimeout(()=>{setNow(new Date().toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}));setRefreshing(false)},500)}return <main className="wrap"><header className="top"><div><div className="eyebrow">Flood Intelligence · Bangkok East</div><h1>ขุมทอง – ลาดกระบัง</h1><div className="muted">Multi-source evidence • freshness gate • deterministic risk engine</div></div><button onClick={refresh}>{refreshing?'กำลังตรวจสอบ…':'Refresh'}</button></header><section className="card hero"><div className="eyebrow">CURRENT STATE</div><div className="state watch">WATCH</div><div>Confidence: <b>LOW — DATA INTEGRATION IN PROGRESS</b></div><p className="analysis">ระบบอยู่ในช่วงเชื่อมต่อแหล่งข้อมูลสด จึงยังไม่สรุปว่าปลอดภัยหรืออันตรายจากค่าที่ไม่ผ่านการตรวจสอบ เมื่อ adapter พร้อม ระบบจะประเมินแนวโน้มระดับน้ำ ฝนสะสม เรดาร์ น้ำท่วมถนน และความสดของข้อมูลก่อนสร้างบทวิเคราะห์ ณ เวลาที่เปิดหน้าเว็บ</p><div className="muted">อัปเดตหน้า: {now||'กำลังอ่านเวลา…'}</div></section><section className="grid"><div className="card"><h2>หลักการวิเคราะห์</h2><div className="row"><span>Freshness</span><b>&lt; 60 นาที</b></div><div className="row"><span>Water trend</span><b>30m / 1h / 3h</b></div><div className="row"><span>State model</span><b>5 ระดับ</b></div></div><div className="card"><h2>สถานะความเสี่ยง</h2><div className="row"><span className="good">NORMAL</span><span>ปกติ</span></div><div className="row"><span className="watch">WATCH</span><span>เฝ้าระวัง</span></div><div className="row"><span className="warn">WARNING → ACTION → EMERGENCY</span></div></div><div className="card"><h2>กติกาข้อมูล</h2><p className="analysis">ข้อมูล stale, suspect หรือ unavailable จะไม่ถูกนำมาอ้างว่าเป็นสถานการณ์ปัจจุบัน และ sensor เดี่ยวจะไม่ใช้ยืนยัน escalation โดยไม่มีหลักฐานประกอบ</p></div></section><section className="card" style={{marginTop:16}}><h2>Source Health</h2>{sources.map(s=><div className="row" key={s.name}><div><div className="source">{s.name}</div><div className="muted">{s.detail}</div></div><span className="tag">{s.status}</span></div>)}</section><section className="card" style={{marginTop:16}}><h2>บทวิเคราะห์ระบบ</h2><p className="analysis">เวอร์ชันนี้เป็น public dashboard foundation สำหรับ GitHub Pages. ขั้นต่อไปคือเชื่อม backend/API gateway เพื่อหลีกเลี่ยง CORS, ซ่อน API keys, normalize schema และเก็บ historical time-series จากนั้น narrative จะถูกสร้างจาก structured evidence หลัง Risk Engine ไม่ใช่ให้ AI สร้างข้อเท็จจริงเอง</p></section><footer className="footer">Decision-support only — ไม่ใช่ประกาศเตือนภัยหรือคำสั่งอพยพอย่างเป็นทางการ</footer></main>}
