'use client';
import {useEffect,useState} from 'react';

type Status='VERIFIED'|'AUTH REQUIRED'|'ENDPOINT REQUIRED';
type Source={name:string,status:Status,detail:string};
const sources:Source[]=[
{name:'BMA Rain / Radar',status:'VERIFIED',detail:'Official DDS source verified: real-time public JSON/HTML catalog; machine endpoint adapter is the next integration step.'},
{name:'BMA Water Level',status:'ENDPOINT REQUIRED',detail:'Official 5-minute Bangkok water-level dataset verified; current live machine endpoint still requires verification.'},
{name:'ThaiWater / HII',status:'VERIFIED',detail:'Official water-information source verified; nearby-station schema and runtime freshness validation still required.'},
{name:'TMD Weather / Radar / NWP',status:'ENDPOINT REQUIRED',detail:'Official TMD weather and radar/NWP source verified; machine contract/credential must be validated before runtime use.'},
{name:'GISTDA Flood',status:'AUTH REQUIRED',detail:'Official flood API contract verified: 1/3/7/30-day flood features plus WMS/WMTS/TMS; full API access may require key/login.'},
{name:'Road Flood',status:'ENDPOINT REQUIRED',detail:'BMA historical road-flood source verified; a current real-time nearby-road machine endpoint is not yet verified.'}
];
export default function Home(){const[now,setNow]=useState('');useEffect(()=>setNow(new Date().toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})),[]);return <main className="wrap"><header className="top"><div><div className="eyebrow">Flood Intelligence · Bangkok East</div><h1>ขุมทอง – ลาดกระบัง</h1><div className="muted">Evidence-first flood intelligence · source readiness dashboard</div></div></header><section className="card hero"><div className="eyebrow">CURRENT SYSTEM STATE</div><div className="state watch">INTEGRATION</div><div>Risk confidence: <b>NOT YET COMPUTED</b></div><p className="analysis">หน้า public นี้ยังไม่ประกาศ WATCH/NORMAL จากข้อมูลจำลอง เพราะ GitHub Pages เป็น static hosting. ตอนนี้ระบบแสดงสถานะความพร้อมของแหล่งข้อมูลที่ตรวจสอบกับแหล่งทางการแล้ว ขั้นต่อไปคือ server-side gateway สำหรับเรียก API จริง ตรวจ freshness/schema แล้วจึงคำนวณความเสี่ยงจากหลักฐานสด.</p><div className="muted">เปิดหน้าเมื่อ: {now||'กำลังอ่านเวลา…'}</div></section><section className="grid"><div className="card"><h2>Runtime gate</h2><div className="row"><span>Fresh observation</span><b>&lt; 60 นาที</b></div><div className="row"><span>Water trend</span><b>30m / 1h / 3h</b></div><div className="row"><span>Cross-source</span><b>≥ 2 signals</b></div></div><div className="card"><h2>สถานะเมื่อ Live</h2><div className="row"><span className="good">NORMAL</span><span>ปกติ</span></div><div className="row"><span className="watch">WATCH</span><span>เฝ้าระวัง</span></div><div className="row"><span className="warn">WARNING → ACTION → EMERGENCY</span></div></div><div className="card"><h2>กติกา</h2><p className="analysis">VERIFIED หมายถึงตรวจพบแหล่ง/contract ทางการแล้ว ไม่ได้หมายความว่ากำลังได้รับข้อมูลสด. คำว่า LIVE จะใช้เฉพาะเมื่อ runtime request สำเร็จ, schema ผ่าน และ timestamp สด.</p></div></section><section className="card" style={{marginTop:16}}><h2>Source Integration Readiness</h2>{sources.map(s=><div className="row" key={s.name}><div><div className="source">{s.name}</div><div className="muted">{s.detail}</div></div><span className="tag">{s.status}</span></div>)}</section><section className="card" style={{marginTop:16}}><h2>เป้าหมาย Live Engine</h2><p className="analysis">Gateway จะ normalize ฝน/เรดาร์, ระดับน้ำ, forecast, satellite flood extent และ road flooding เป็น evidence เดียวกัน จากนั้นคำนวณ trend + freshness + data quality ก่อนสร้างบทวิเคราะห์ ณ เวลาที่เปิดเว็บ. API key จะไม่ถูกฝังใน JavaScript ฝั่ง browser.</p></section><footer className="footer">Decision-support only — ไม่ใช่ประกาศเตือนภัยหรือคำสั่งอพยพอย่างเป็นทางการ</footer></main>}
